### PR TITLE
Expand graph to full width of page

### PR DESCRIPTION
**Pull request by 0xChijioke**
Changes:
 - This PR adjusts the layout to allow the graph to fill the entire width of the view.

 - Shifts the vector selection menu downward to maintain proximity to the adjustable vectors table.

 - Places the action button to the right of the existing buttons.

Initial view
image

Full width
image

This pull request focuses on addressing issue #54  while simultaneously removing layout modifications proposed in #52 . Unfortunately, the closed PR could not be reopened. This pull request builds upon the changes introduced in PR #53.

### CODE REVIEW

**Review by escottalexander — CHANGES_REQUESTED** [review]
This is great! Works just how I was envisioning. There is a large gap on my screen between the graph and the selectable vectors though: 
image

Sorry, I know it is hard to test larger screens.

**Comment by 0xChijioke** [comment]
> This is great! Works just how I was envisioning. There is a large gap on my screen between the graph and the selectable vectors though: image
> 
> Sorry, I know it is hard to test larger screens.

Thanks for the feedback! 
Glad it aligns with your vision. 
Will fix the gap issue ASAP. 
Appreciate your understanding!

**Comment by 0xChijioke** [comment]
@escottalexander I've addressed the gap issue on larger screens. 
Please have a look and confirm if everything looks good on your end.

**Review by escottalexander — APPROVED** [review]
Nice work on this one. Looks great!

**Pull request merged**
