### PR TITLE
Added vectors have slideable weights and redraws impact graph.

### PR DESCRIPTION
**Pull request by 0xChijoke**
This PR hooks the slidable vector weight up and redraws the graph when the weight of added vectors are adjusted  to resolve issue #17 
This PR introduces a temporary solution for #14 by setting the chain to optimism.

### CODE REVIEW

**Comment by escottalexander** [comment]
@0xChijoke I don't have time to look at your code just now but one thing I noticed is that the sliders are very "jumpy". Prior to these changes they were very smooth. Any ideas why that would be the case?

Otherwise this is looking really great!

**Comment by 0xChijoke** [comment]
@escottalexander The slider now triggers an API call with each change, which might raise performance issues. To address this, I implemented a 300-millisecond input debounce.

**Comment by 0xChijoke** [comment]
@escottalexander Another alternative is to debounce the API calls directly, shifting any lag to the graph rendering process.

**Review by escottalexander — APPROVED** [review]
Approving and merging. I feel strongly that we need to discover a solution to the stickiness of the slider.

**Pull request merged**
